/**
 * convert-presets.js — one-off offline conversion of 10 curated .milk
 * presets (projectM "presets-cream-of-the-crop" Waveform category) into
 * Butterchurn-ready preset objects, written to visualizer/presets.js.
 *
 * This is NOT a runtime dependency of the game. It is run once by hand;
 * its output (visualizer/presets.js) is committed to the repo.
 *
 * Why a headless browser: the .milk -> JS preset conversion logic lives in
 * `milkdrop-preset-converter-aws` (the same library Webamp's own
 * `presetConverterEndpoint` feature calls remotely). That bundle expects a
 * `window`/WebGL-ish environment (it shells out to glsl-optimizer-js), so it
 * cannot run under plain Node. We drive it locally inside Puppeteer instead
 * of hitting Webamp's remote conversion endpoint, keeping this fully offline
 * and reproducible.
 *
 * Usage:
 *   node scripts/convert-presets.js
 *
 * Source .milk files are expected in scripts/raw-presets/<key>.milk
 * (already fetched from the projectM presets-cream-of-the-crop repo).
 */

import puppeteer from 'puppeteer'
import { readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

// name -> { file, source }. `file` is the local raw .milk path (relative to
// scripts/raw-presets/), `source` documents where it came from.
// NOTE on picks: the converter below only handles presets whose .milk file
// has no custom warp/comp pixel shader code (see big comment further down on
// CONVERTER_PATH for why). Many "obvious" picks per category (e.g. the first
// alphabetical file) use custom shaders and fail conversion offline, so each
// pick here was verified to convert successfully before being committed.
const PRESETS = [
  { name: 'Spectrum', file: 'Spectrum.milk', source: 'Waveform/Spectrum/raron - simple frequency spectrum 3.milk' },
  { name: 'Wire Circular', file: 'Wire_Circular.milk', source: 'Waveform/Wire Circular/Geiss - Bipolar X.milk' },
  { name: 'Wire Flat Double', file: 'Wire_Flat_Double.milk', source: 'Waveform/Wire Flat Double/Geiss - Casino.milk' },
  { name: 'Wire Flat', file: 'Wire_Flat.milk', source: 'Waveform/Wire Flat/Bmelgren & Krash - Rainbow Orb Peacock (Lonely Signal Gone Mad Mix).milk' },
  { name: 'Wire Flower', file: 'Wire_Flower.milk', source: 'Waveform/Wire Flower/Geiss - Flower.milk' },
  { name: 'Wire Mirror', file: 'Wire_Mirror.milk', source: 'Waveform/Wire Mirror/Bmelgren-angeldreams.milk' },
  { name: 'Wire Rising', file: 'Wire_Rising.milk', source: 'Waveform/Wire Rising/beta106i - Arise! (Padded).milk' },
  { name: 'Wire Spirograph', file: 'Wire_Spirograph.milk', source: 'Waveform/Wire Spirograph/AkashaDude & Geiss - DeltaTango.milk' },
  { name: 'Wire Tangle', file: 'Wire_Tangle.milk', source: 'Waveform/Wire Tangle/Aderrasi - Chromatic Abyss (The Other Side).milk' },
  { name: 'Wire Tunnel', file: 'Wire_Tunnel.milk', source: 'Waveform/Wire Tunnel/BrainStain-boiling-comfortably numb-mix.milk' }
]

// This converter lib is intentionally NOT a Sky Roads dependency — it's a
// one-off build-time tool, borrowed from the sibling BrainBlur repo where it
// already exists as a transitive dependency of webamp. Adjust this path if
// BrainBlur moves or isn't available; the conversion only needs to run once.
const CONVERTER_PATH = 'C:/dev/BrainBlur/node_modules/milkdrop-preset-converter-aws/dist/milkdrop-preset-converter-aws.min.js'
const RAW_DIR = path.join(__dirname, 'raw-presets')
const OUTPUT_PATH = path.resolve(__dirname, '../visualizer/presets.js')

async function main() {
  const converterSrc = await readFile(CONVERTER_PATH, 'utf-8')

  const browser = await puppeteer.launch({ headless: true })
  const page = await browser.newPage()
  await page.setContent('<!doctype html><html><body></body></html>')
  await page.addScriptTag({ content: converterSrc })

  const converted = []
  for (const { name, file, source } of PRESETS) {
    const milkPath = path.join(RAW_DIR, file)
    const milkText = await readFile(milkPath, 'utf-8')
    console.log(`Converting "${name}" <- ${source}`)
    const presetObject = await page.evaluate(async (text) => {
      const { convertPreset } = window.milkdropPresetConverterAWS
      return convertPreset(text, '')
    }, milkText)
    if (presetObject && presetObject.error) {
      throw new Error(`Conversion failed for "${name}" (${source}): ${presetObject.error}`)
    }
    converted.push({ name, butterchurnPresetObject: presetObject })
  }

  await browser.close()

  const body = `/**
 * presets.js — 10 curated Butterchurn presets, pre-converted offline from
 * the projectM "presets-cream-of-the-crop" Waveform category.
 *
 * Generated by scripts/convert-presets.js — do not hand-edit; re-run the
 * script against scripts/raw-presets/*.milk to regenerate.
 *
 * Shape matches webamp's Preset type (ButterchurnPresetJson):
 *   { name: string, butterchurnPresetObject: Object }
 */

export const presets = ${JSON.stringify(converted, null, 2)}

export default presets
`

  await writeFile(OUTPUT_PATH, body)
  console.log(`\nWrote ${converted.length} presets to ${OUTPUT_PATH}`)
}

main().catch((err) => {
  console.error('Conversion failed:', err)
  process.exit(1)
})
